# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_azIJj4NdV8krK2oNWPSE8A4mARErU2t
"""

def exibir_menu():
    print("\nBem-vindo à Calculadora!")
    print("Operações disponíveis:")
    print("1. Soma")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("5. Sair")

def obter_numero(mensagem):
    while True:
        try:
            return float(input(mensagem))
        except ValueError:
            print("Entrada inválida. Digite um número válido.")

def calculadora():
    while True:
        exibir_menu()
        opcao = input("Escolha uma opção (1-5): ")

        if opcao == "5":
            print("Encerrando a calculadora. Até mais!")
            break

        if opcao not in {"1", "2", "3", "4"}:
            print("Opção inválida. Tente novamente.")
            continue

        num1 = obter_numero("Digite o primeiro número: ")
        num2 = obter_numero("Digite o segundo número: ")

        if opcao == "1":
            print(f"Resultado: {num1 + num2}")
        elif opcao == "2":
            print(f"Resultado: {num1 - num2}")
        elif opcao == "3":
            print(f"Resultado: {num1 * num2}")
        elif opcao == "4":
            if num2 == 0:
                print("Erro: Divisão por zero!")
            else:
                print(f"Resultado: {num1 / num2}")

if __name__ == "__main__":
    calculadora()